# WandB stuff, change according to user
use_wandb: True
wandb_project_name: transfer_to_continual_learning
wandb_profile: lukebailey

# Memory set hyperparameters
memory_set_manager: random
p: 1
use_memory_set: False

# Continual learning hyperparameters
#learning_manager: mnist_split
learning_manager: cifar10_split
#learning_manager: cifar10_full

# Training hyperparameters
lr: 0.001
#lr: 0.01
batch_size: 256
random_seed: 56
epochs: 50

# Model arch 
#model:
#  type: mlp 
#  params: 
#    sizes: [784, 1000, 10] 
#    acts: [relu]

#Example CNN
model: 
  type: cnn
  params: 
    in_channels: 3 
    out_channels: 10
    l1_out_channels: 16
    l2_out_channels: 16
    l3_out_channels: 32
    l4_out_channels: 32

model_load_dir: ./models/cifar_10_split_done/16_16_32_32
# For models trained on individual tasks, used for calculating forward transfer
sep_model_load_dir: ./models/cifar_10_split_done/gold

# Logging information
experiment_tag: "TEST"